### PR TITLE
resolves #42

### LINKED ISSUE #42: [Bug] Content Word Count is not Updated
**Describe the bug**
The "Stoplight" for content length remains red with "You haven't entered any content yet!" regardless of how many words are in the post or page. 

**To Reproduce**
1. Install WordPress with BoldGrid Easy SEO
2. Create a post or page and enter in any amount of content
3. Note that the word count remains zero
4. Save Draft or Publish, and note that the word count remains zero.

**Expected behavior**
The word count should continue to update via Ajax process, and after saving a draft or publishing
**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This issue was [reported in the BoldGrid User Forums](https://www.boldgrid.com/support/question/social-image-content-word-count-are-not-updating/).

### PR DESCRIPTION
**Pull request by jamesros161**

### CODE REVIEW

File: assets/js/bgseo.js [hunk 1]
```diff
@@ -752,9 +752,12 @@ BOLDGRID.SEO = BOLDGRID.SEO || {};
 				contentEditor = self.getTinymce();
 
 			if ( ! contentEditor || contentEditor.isHidden() ) {
-				text =  api.Editor.element.val();
+				text = api.Editor.element.val();
 			} else {
 				text = contentEditor.getContent( { format: 'raw' } );
+				
+				// Sometimes, on initial page load, the 'getContent' method doesn't return anything.
```
Comment (bwmarkle) [inline assets/js/bgseo.js:759]: > // Sometimes, on initial page load, the 'getContent' method doesn't return anything.

Do we know why this is? Are we adding a band-aid because we're not quite sure what's happening?

**Review by bwmarkle — CHANGES_REQUESTED** [review]
Also, has QA had time to test?

File: assets/js/bgseo.js (hunk 1 above)
Comment (jamesros161) [reply assets/js/bgseo.js:759]: QA has tested this.

This is just because of timing.... the value of the `api.Editor.element` is present as soon as the page is loaded, but the `contentEditor.getContent()` method returns the contents AFTER they've been loaded into the tinyMCE application.

The preference is to use the text  returned by the `getContent()` method, because it more accurately reflects changes as the user is making them AFTER the initial page load. However the usage of the `api.Editor.element.val()` is totally acceptable as a fallback for when the `getContent()` method is not populated yet.

**Review by bwmarkle — APPROVED** [review]
