### PR TITLE
php 7.4 implode fix. Fixes #27

### LINKED ISSUE #27: PHP 7.4 - PHP Deprecated:  implode(): Passing glue string after array is deprecated.
**Describe the bug**
When activating BoldGrid SEO through the inspirations process, the following error is generated

**Environment Details**
Wordpress Version: 5.5-beta3
PHP Version: 7.4

**To Reproduce**
1. Install WP 5.5-beta3
2. Enable WP_DEBUG
3. Install BoldGrid Inspirations
4. Proceed through the installation process selecting a v1 theme
5. See error

**Expected behavior**
Expect to not receive a ton of PHP Notices.

**Error Reported**
[29-Jul-2020 19:10:29 UTC] PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/tu55testing/wp-content/plugins/boldgrid-easy-seo/includes/class-boldgrid-seo-util.php on line 102
[29-Jul-2020 19:10:29 UTC] PHP Stack trace:
[29-Jul-2020 19:10:29 UTC] PHP   1. {main}() /var/www/html/tu55testing/index.php:0
[29-Jul-2020 19:10:29 UTC] PHP   2. require() /var/www/html/tu55testing/index.php:17
[29-Jul-2020 19:10:29 UTC] PHP   3. require_once() /var/www/html/tu55testing/wp-blog-header.php:19
[29-Jul-2020 19:10:29 UTC] PHP   4. include() /var/www/html/tu55testing/wp-includes/template-loader.php:106
[29-Jul-2020 19:10:29 UTC] PHP   5. get_template_part() /var/www/html/tu55testing/wp-content/themes/boldgrid-callaway/base.php:17
[29-Jul-2020 19:10:29 UTC] PHP   6. locate_template() /var/www/html/tu55testing/wp-includes/general-template.php:204
[29-Jul-2020 19:10:29 UTC] PHP   7. load_template() /var/www/html/tu55testing/wp-includes/template.php:676
[29-Jul-2020 19:10:29 UTC] PHP   8. require() /var/www/html/tu55testing/wp-includes/template.php:732
[29-Jul-2020 19:10:29 UTC] PHP   9. wp_head() /var/www/html/tu55testing/wp-content/themes/boldgrid-callaway/templates/head.php:16
[29-Jul-2020 19:10:29 UTC] PHP  10. do_action() /var/www/html/tu55testing/wp-includes/general-template.php:2992
[29-Jul-2020 19:10:29 UTC] PHP  11. WP_Hook->do_action() /var/www/html/tu55testing/wp-includes/plugin.php:478
[29-Jul-2020 19:10:29 UTC] PHP  12. WP_Hook->apply_filters() /var/www/html/tu55testing/wp-includes/class-wp-hook.php:311
[29-Jul-2020 19:10:29 UTC] PHP  13. Boldgrid_Seo_Admin->wp_head() /var/www/html/tu55testing/wp-includes/class-wp-hook.php:287
[29-Jul-2020 19:10:29 UTC] PHP  14. do_action() /var/www/html/tu55testing/wp-content/plugins/boldgrid-easy-seo/includes/class-boldgrid-seo-admin.php:125
[29-Jul-2020 19:10:29 UTC] PHP  15. WP_Hook->do_action() /var/www/html/tu55testing/wp-includes/plugin.php:478
[29-Jul-2020 19:10:29 UTC] PHP  16. WP_Hook->apply_filters() /var/www/html/tu55testing/wp-includes/class-wp-hook.php:311
[29-Jul-2020 19:10:29 UTC] PHP  17. Boldgrid_Seo_Admin->meta_og_description() /var/www/html/tu55testing/wp-includes/class-wp-hook.php:287
[29-Jul-2020 19:10:29 UTC] PHP  18. Boldgrid_Seo_Admin->get_meta_description() /var/www/html/tu55testing/wp-content/plugins/boldgrid-easy-seo/includes/class-boldgrid-seo-admin.php:359
[29-Jul-2020 19:10:29 UTC] PHP  19. Boldgrid_Seo_Util->get_sentences() /var/www/html/tu55testing/wp-content/plugins/boldgrid-easy-seo/includes/class-boldgrid-seo-admin.php:346
[29-Jul-2020 19:10:29 UTC] PHP  20. Boldgrid_Seo_Util->construct_sentences() /var/www/html/tu55testing/wp-content/plugins/boldgrid-easy-seo/includes/class-boldgrid-seo-util.php:77
[29-Jul-2020 19:10:29 UTC] PHP  21. implode() /var/www/html/tu55testing/wp-content/plugins/boldgrid-easy-seo/includes/class-boldgrid-seo-util.php:102

**Additional context**
This issue is related to inspirations [#76](https://github.com/BoldGrid/boldgrid-inspirations/issues/76).
These error messages were generated at the same time in testing.

### PR DESCRIPTION
**Pull request by bwmarkle**

### CODE REVIEW

File: includes/class-boldgrid-seo-util.php [hunk 1]
```diff
@@ -99,7 +99,7 @@ public function construct_sentences( $sentences ) {
 			// Check out a single sentence returned.
 			case 1 :
 				// Create string with our setence.
```
Comment (cssjoe) [inline includes/class-boldgrid-seo-util.php:101]: Typo: "setence" => "sentence".
